language: php
php:
  - "hhvm"
  - "7.0"
  - "5.6"
  - "5.5"

services:
  - memcached
  - redis-server

env:
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

matrix:
  fast_finish: true

sudo: false

before_script:
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer install --dev --prefer-dist --no-interaction

script:
    - php vendor/bin/phpunit

after_success:
    - codecov
