language: php
php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5

sudo: false

env:
  global:
    - COMPOSER_COMMAND="composer install --prefer-dist"
  matrix:
    - SYMFONY_VERSION=2.6.*
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: COMPOSER_COMMAND="composer update --prefer-lowest --prefer-stable" && SYMFONY_VERSION=2.7.*

before_install:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update

install:
  - travis_retry ${COMPOSER_COMMAND} --no-interaction

script:
  - php vendor/bin/phpunit

after_success:
  - codecov
