language: php
php:
  - "hhvm"
  - "7.0"
  - "5.6"
  - "5.5"

sudo: required

services:
  - memcached
  - redis-server

env:
  global:
    - COMPOSER_COMMAND="composer install --prefer-dist"
  matrix:
    - SYMFONY_VERSION=2.6.*
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: COMPOSER_COMMAND="composer update --prefer-lowest --prefer-stable" && SYMFONY_VERSION=2.7.*

before_script:
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && `php-config --vernum` -ge 70000 ]]; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu; else echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - travis_retry ${COMPOSER_COMMAND} --no-interaction
  # must be set after composer to avoid issue with autoloading
  - echo "apc.enable_cli=On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
    - php vendor/bin/phpunit

after_success:
    - codecov
