
services:
    cache.doctrine_adapter.abstract.apc:
        class: Doctrine\Common\Cache\ApcCache

    cache.doctrine_adapter.abstract.array:
        class: Doctrine\Common\Cache\ArrayCache

    cache.doctrine_adapter.abstract.file_system:
        class: Doctrine\Common\Cache\FilesystemCache

    cache.doctrine_adapter.abstract.memcache:
        class: Doctrine\Common\Cache\MemcacheCache

    cache.doctrine_adapter.abstract.memcached:
        class: Doctrine\Common\Cache\MemcachedCache

    cache.doctrine_adapter.abstract.redis:
        class: Doctrine\Common\Cache\RedisCache

    cache.doctrine_adapter.abstract.php_file:
        class: Doctrine\Common\Cache\PhpFileCache

    cache.doctrine_adapter.abstract.win_cache:
        class: Doctrine\Common\Cache\WinCacheCache

    cache.doctrine_adapter.abstract.xcache:
        class: Doctrine\Common\Cache\XcacheCache

    cache.doctrine_adapter.zend_data:
        class: Doctrine\Common\Cache\ZendDataCache
