services:
  cache.factory.apc:
    class: Cache\AdapterBundle\Factory\ApcFactory
  cache.factory.uapc:
    class: Cache\AdapterBundle\Factory\ApcuFactory
  cache.factory.array:
    class: Cache\AdapterBundle\Factory\ArrayFactory
  cache.factory.doctrine_redis:
    class: Cache\AdapterBundle\Factory\DoctrineRedisFactory
  cache.factory.filesystem:
    class: Cache\AdapterBundle\Factory\FilesystemFactory
  cache.factory.memcached:
    class: Cache\AdapterBundle\Factory\MemcachedFactory
  cache.factory.predis:
    class: Cache\AdapterBundle\Factory\PredisFactory
  cache.factory.redis:
    class: Cache\AdapterBundle\Factory\RedisFactory
  cache.factory.void:
    class: Cache\AdapterBundle\Factory\VoidFactory



