
services:
    aequasi_cache.abstract.apc:
        class: Doctrine\Common\Cache\ApcCache
        abstract: true

    aequasi_cache.abstract.array:
        class: Doctrine\Common\Cache\ArrayCache
        abstract: true

    aequasi_cache.abstract.file_system:
        class: Doctrine\Common\Cache\FilesystemCache
        abstract: true

    aequasi_cache.abstract.memcache:
        class: Doctrine\Common\Cache\MemcacheCache
        abstract: true

    aequasi_cache.abstract.memcached:
        class: Doctrine\Common\Cache\MemcachedCache
        abstract: true

    aequasi_cache.abstract.redis:
        class: Doctrine\Common\Cache\RedisCache
        abstract: true

    aequasi_cache.abstract.php_file:
        class: Doctrine\Common\Cache\PhpFileCache
        abstract: true

    aequasi_cache.abstract.win_cache:
        class: Doctrine\Common\Cache\WinCacheCache
        abstract: true

    aequasi_cache.abstract.xcache:
        class: Doctrine\Common\Cache\XcacheCache
        abstract: true

    aequasi_cache.zend_data:
        class: Doctrine\Common\Cache\ZendDataCache
        abstract: true
